# -*- coding: utf-8 -*-
"""Another copy of parasitic disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FazThjKnkEwQJW6ErSrokNxNWtJ9CpWS
"""


# Load datasets
import pandas as pd
# Added encoding='latin-1' to handle the different file encoding
authors_df = pd.read_csv("data/authors.schistosomiasis.csv",encoding='latin-1')
relevant_articles_final = pd.read_csv("data/relevant_articles_final.csv",encoding='latin-1')

# Replace missing forenames with a placeholder (e.g., 'Unknown')
authors_df['AuthorForename'] = authors_df['AuthorForename'].fillna('Unknown')

import matplotlib.pyplot as plt
# Ensure the 'Year' column exists in the dataset
if 'Year' not in relevant_articles_final.columns:
    raise KeyError("The dataset must contain a 'Year' column.")

# Group by 'Year' and count the number of PMIDs (publications)
yearly_publications = relevant_articles_final.groupby('Year')['PMID'].count().reset_index()
yearly_publications.rename(columns={'PMID': 'PublicationCount'}, inplace=True)

# Find the year with the highest number of publications
max_year = yearly_publications.loc[yearly_publications['PublicationCount'].idxmax()]

# Create a figure
plt.figure(figsize=(12, 6))

# Plot the bar chart
colors = ['red' if year == max_year['Year'] else 'skyblue' for year in yearly_publications['Year']]
plt.bar(yearly_publications['Year'], yearly_publications['PublicationCount'], color=colors, alpha=0.7, label='Number of Articles')

# Plot the line chart
plt.plot(yearly_publications['Year'], yearly_publications['PublicationCount'], color='blue', marker='o', label='Publications Trend')

# Highlight the highest year
plt.annotate(
    f"Highest: {int(max_year['Year'])} ({max_year['PublicationCount']})",
    xy=(max_year['Year'], max_year['PublicationCount']),
    xytext=(max_year['Year'], max_year['PublicationCount'] + 30),
    ha='center',
    fontsize=12,
    arrowprops=dict(facecolor='black', arrowstyle='->')
)

# Add labels and title
plt.xlabel('Year', fontsize=14)
plt.ylabel('Number of Publications', fontsize=14)
plt.title('Number of Articles Published per Year', fontsize=16)
plt.xticks(rotation=45)
plt.legend()

# Add a grid for better readability
plt.grid(alpha=0.4, linestyle='--')

# Adjust layout and display the plot
plt.tight_layout()
plt.show()